gpt35_turbo_1106:
  prompt_template: "gpt35_turbo_1106/basic_function_prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-3.5-turbo-1106"
    max_tokens: 50
    temperature: 0
    function_call:
      name: "print_best_model"
    functions:
      - name: "print_best_model"
        description: "Print the best model given the preferred output."
        parameters:
          type: "object"
          properties:
            best_output:
              type: "string"
              description: "Name of the best output, should be 'Output (a)' or 'Output (b)'"
        "required": [ "best_output" ]
  completion_parser_kwargs:
    outputs_to_match:
      1: '(?i)output \(a\)'
      2: '(?i)output \(b\)'
  batch_size: 1
